using Game.Structures.Api;
using Unity.Mathematics;

namespace Game.Structures.Runtime
{
    /// <summary>
    /// Lightweight request for detail that should be generated by a presentation mesh system rather
    /// than voxel authoring. This is intentionally data-only; it does not create GameObjects.
    /// </summary>
    public struct DecorationProceduralMeshRequest
    {
        public GeneratedPropId Id;
        public DecorationPropFamily Family;
        public DecorationBounds Bounds;
        public int3 Facing;
        public uint Variant;
    }

    public static class DecorationProceduralMeshHookPlanner
    {
        public static DecorationProceduralMeshRequest[] Collect(DecorationPlacement[] placements)
        {
            if (placements == null)
                return new DecorationProceduralMeshRequest[0];

            int count = 0;
            for (int i = 0; i < placements.Length; i++)
            {
                if (placements[i].IsWellFormed &&
                    placements[i].Backend == DecorationRenderBackend.ProceduralMesh)
                    count++;
            }

            var requests = new DecorationProceduralMeshRequest[count];
            int output = 0;
            for (int i = 0; i < placements.Length; i++)
            {
                DecorationPlacement placement = placements[i];
                if (!placement.IsWellFormed || placement.Backend != DecorationRenderBackend.ProceduralMesh)
                    continue;

                requests[output++] = new DecorationProceduralMeshRequest
                {
                    Id = placement.Id,
                    Family = placement.Family,
                    Bounds = placement.Bounds,
                    Facing = placement.Facing,
                    Variant = placement.Variant,
                };
            }
            return requests;
        }
    }

    public enum DecorationEffectKind : byte
    {
        Light = 0,
        Particles = 1,
    }

    public struct DecorationEffectHook
    {
        public GeneratedPropId Id;
        public DecorationPropFamily Family;
        public DecorationEffectKind Kind;
        public float3 PositionVoxel;
        public uint Variant;
    }

    /// <summary>
    /// Produces optional presentation effects from semantic interaction flags. Condition policy can
    /// suppress emission without changing deterministic prop identity or placement.
    /// </summary>
    public static class DecorationEffectHookPlanner
    {
        public static DecorationEffectHook[] Collect(
            DecorationPlacement[] placements,
            in DecorationContext context)
        {
            if (placements == null || !context.IsWellFormed)
                return new DecorationEffectHook[0];

            DecorationPresentationProfile profile = DecorationContextProfiles.ResolvePresentation(in context);
            int count = 0;
            for (int i = 0; i < placements.Length; i++)
            {
                DecorationPlacement placement = placements[i];
                if (!placement.IsWellFormed)
                    continue;
                if (profile.EmitsLight &&
                    (placement.Interaction & DecorationInteractionFlags.EmitsLight) != 0)
                    count++;
                if (profile.DamageLevel < 4 &&
                    (placement.Interaction & DecorationInteractionFlags.EmitsParticles) != 0)
                    count++;
            }

            var hooks = new DecorationEffectHook[count];
            int output = 0;
            for (int i = 0; i < placements.Length; i++)
            {
                DecorationPlacement placement = placements[i];
                if (!placement.IsWellFormed)
                    continue;

                float3 position = EffectPosition(in placement);
                if (profile.EmitsLight &&
                    (placement.Interaction & DecorationInteractionFlags.EmitsLight) != 0)
                {
                    hooks[output++] = Hook(in placement, DecorationEffectKind.Light, position);
                }
                if (profile.DamageLevel < 4 &&
                    (placement.Interaction & DecorationInteractionFlags.EmitsParticles) != 0)
                {
                    hooks[output++] = Hook(in placement, DecorationEffectKind.Particles, position);
                }
            }
            return hooks;
        }

        private static float3 EffectPosition(in DecorationPlacement placement)
        {
            DecorationBounds bounds = placement.Bounds;
            return new float3(
                (bounds.Min.x + bounds.MaxExclusive.x) * 0.5f,
                bounds.MaxExclusive.y - 0.5f,
                (bounds.Min.z + bounds.MaxExclusive.z) * 0.5f);
        }

        private static DecorationEffectHook Hook(
            in DecorationPlacement placement,
            DecorationEffectKind kind,
            float3 position) => new DecorationEffectHook
        {
            Id = placement.Id,
            Family = placement.Family,
            Kind = kind,
            PositionVoxel = position,
            Variant = placement.Variant,
        };
    }
}
