from pathlib import Path


def replace_once(path_text, old, new, label):
    path = Path(path_text)
    text = path.read_text()
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected exactly one source match, found {count}")
    path.write_text(text.replace(old, new, 1))


replace_once(
    "Assets/VoxelEngine/Rendering/Runtime/SurfaceExtraction/CpuTransvoxelChunkCache.cs",
    '''            bool hasDesired = _desiredVersions.TryGetValue(coordinate, out ulong desired);\n            if (_entries.TryGetValue(coordinate, out Entry entry) && entry.Ready)\n            {\n                // Keep the previous mesh drawable while a newer authoritative generation waits\n                // for this ring to need it. Parking background work must never turn an edit into\n                // stale visible geometry when the chunk comes back into the active shell.\n                if (hasDesired && desired > entry.SourceVersion) MarkDirty(coordinate);\n                if (entry.IndexCount == 0) return;\n                entry.LastUsedFrame = frame;\n                _visible.Add(entry);\n                return;\n            }\n\n            // A current known-empty result is complete, not a visual hole. Any other in-band\n            // visible coordinate is demand: reactivate work that discovery parked while the\n            // coordinate belonged to another LOD ring (or was evicted under pressure).\n            if (_emptyVersions.TryGetValue(coordinate, out ulong emptyVersion)\n                && (!hasDesired || emptyVersion >= desired))\n                return;\n\n            MarkDirty(coordinate);\n            MissingVisibleCount++;\n''',
    '''            bool hasDesired = _desiredVersions.TryGetValue(coordinate, out ulong desired);\n            bool currentGenerationInFlight = CurrentBuildCoversDesiredGeneration(\n                coordinate, hasDesired, desired);\n            if (_entries.TryGetValue(coordinate, out Entry entry) && entry.Ready)\n            {\n                // Keep the previous mesh drawable while a newer authoritative generation waits\n                // for this ring to need it. Parking background work must never turn an edit into\n                // stale visible geometry when the chunk comes back into the active shell. Do not\n                // enqueue the same generation again while its replacement is already building or\n                // awaiting upload; admission removes active builds from _dirty, so visibility\n                // would otherwise recreate a permanent duplicate rebuild loop every frame.\n                if (hasDesired && desired > entry.SourceVersion && !currentGenerationInFlight)\n                    MarkDirty(coordinate);\n                if (entry.IndexCount == 0) return;\n                entry.LastUsedFrame = frame;\n                _visible.Add(entry);\n                return;\n            }\n\n            // A current known-empty result is complete, not a visual hole. Any other in-band\n            // visible coordinate is demand: reactivate work that discovery parked while the\n            // coordinate belonged to another LOD ring (or was evicted under pressure). An active\n            // build/pending upload already satisfies that demand for its exact source generation.\n            if (_emptyVersions.TryGetValue(coordinate, out ulong emptyVersion)\n                && (!hasDesired || emptyVersion >= desired))\n                return;\n\n            if (!currentGenerationInFlight) MarkDirty(coordinate);\n            MissingVisibleCount++;\n''',
    "visibility current-generation admission",
)

replace_once(
    "Assets/VoxelEngine/Rendering/Runtime/SurfaceExtraction/CpuTransvoxelChunkCache.cs",
    '''        private void ParkDirty(int3 chunk)\n        {\n            _dirty.Remove(chunk);\n            _queuedDirty.Remove(chunk);\n            _queuedAtSeconds.Remove(chunk);\n            // Intentionally retain _desiredVersions: discovery/edit state remains authoritative,\n            // and CollectVisibleCoordinate will reactivate it if this chunk enters the ring.\n        }\n\n        public static int ShardForChunk(int3 chunk, int shardCount)\n''',
    '''        private void ParkDirty(int3 chunk)\n        {\n            _dirty.Remove(chunk);\n            _queuedDirty.Remove(chunk);\n            _queuedAtSeconds.Remove(chunk);\n            // Intentionally retain _desiredVersions: discovery/edit state remains authoritative,\n            // and CollectVisibleCoordinate will reactivate it if this chunk enters the ring.\n        }\n\n        private bool CurrentBuildCoversDesiredGeneration(int3 chunk, bool hasDesired, ulong desired)\n        {\n            return _build.Active && _build.Coordinate.Equals(chunk)\n                && (!hasDesired || _build.SourceVersion >= desired);\n        }\n\n        public static int ShardForChunk(int3 chunk, int shardCount)\n''',
    "current build desired generation helper",
)

replace_once(
    "Assets/Tests/EditMode/SurfaceRingBuildAdmissionTests.cs",
    '''        [Test]\n        public void OutOfBandDiscoveryParksUntilChunkBecomesVisibleInRing()\n''',
    '''        [Test]\n        public void VisibleCurrentGenerationBuildDoesNotQueueDuplicateAdmission()\n        {\n            using var cache = new CpuTransvoxelChunkCache(1)\n            {\n                MinViewDistanceMetres = 0f,\n                MaxViewDistanceMetres = 96f,\n                ShardCount = 1,\n                ShardIndex = 0,\n            };\n            cache.SetClipmapWindow(int3.zero, 8);\n\n            MethodInfo discover = typeof(CpuTransvoxelChunkCache).GetMethod(\n                "DiscoverSurfaceBricks", BindingFlags.Instance | BindingFlags.NonPublic);\n            MethodInfo select = typeof(CpuTransvoxelChunkCache).GetMethod(\n                "BeginNearestBuild", BindingFlags.Instance | BindingFlags.NonPublic);\n            Assert.NotNull(discover);\n            Assert.NotNull(select);\n\n            // Interior brick coordinates admit exactly chunk (0,0,0), avoiding border-neighbour\n            // discovery so the active-build assertion is unambiguous.\n            int admitted = (int)discover.Invoke(cache, new object[]\n            {\n                new List<int3> { new int3(1, 1, 1) }\n            });\n            Assert.AreEqual(1, admitted);\n\n            var cameraObject = new GameObject("SurfaceRingBuildAdmissionTests.ActiveCamera");\n            var camera = cameraObject.AddComponent<Camera>();\n            try\n            {\n                camera.transform.position = new Vector3(0f, 0f, -10f);\n                camera.transform.LookAt(Vector3.zero);\n                camera.nearClipPlane = 0.3f;\n                camera.farClipPlane = 200f;\n\n                bool selected = (bool)select.Invoke(cache, new object[]\n                {\n                    camera,\n                    0.1f,\n                    Time.realtimeSinceStartupAsDouble + 1.0,\n                });\n                Assert.True(selected);\n                Assert.AreEqual(1, cache.DirtyCount,\n                    "The selected generation should be represented only by the active build.");\n\n                Plane[] planes = GeometryUtility.CalculateFrustumPlanes(camera);\n                cache.BeginVisibilityCollection();\n                cache.CollectVisibleCoordinate(int3.zero, planes,\n                    camera.transform.position, 0.1f, 1);\n\n                Assert.AreEqual(1, cache.MissingVisibleCount);\n                Assert.AreEqual(1, cache.DirtyCount,\n                    "Visibility requeued the same source generation while it was already in flight.");\n            }\n            finally\n            {\n                UnityEngine.Object.DestroyImmediate(cameraObject);\n            }\n        }\n\n        [Test]\n        public void OutOfBandDiscoveryParksUntilChunkBecomesVisibleInRing()\n''',
    "active generation duplicate admission regression",
)
