from pathlib import Path

path = Path("Assets/VoxelEngine/Rendering/Runtime/SurfaceExtraction/CpuTransvoxelChunkCache.cs")
text = path.read_text()
old = '''            int edge = VoxelReadGrid.BlocksPerRegionEdge;\n            int3 cacheMaxExclusive = cacheOrigin + BrickCacheEdge;\n            int3 minRegion = cacheOrigin >> VoxelReadGrid.BlocksPerRegionEdgeLog2;\n            int3 maxRegion = (cacheMaxExclusive - 1) >> VoxelReadGrid.BlocksPerRegionEdgeLog2;\n\n            for (int rz = minRegion.z; rz <= maxRegion.z; rz++)\n            for (int ry = minRegion.y; ry <= maxRegion.y; ry++)\n            for (int rx = minRegion.x; rx <= maxRegion.x; rx++)\n            {\n                int3 regionCoord = new(rx, ry, rz);\n                bool pinnedRegion = source.TryPinRegionBlockRefs(\n                    regionCoord, out PinnedRegionBlockRefs pinned);\n                _exactMetadataRegionCoverage.RecordRequiredRegion(pinnedRegion);\n                if (!pinnedRegion) continue;\n                if (_pinnedRegionCount >= MaxExactSnapshotRegions)\n                {\n                    source.ReleasePinnedRegion(in pinned.Pin);\n                    ReleasePinnedRegionMetadataImmediate();\n                    throw new InvalidOperationException(\n                        "Exact snapshot exceeded the 3x3x3 pinned-region bound.");\n                }\n                _pinnedRegionBlockRefs[_pinnedRegionCount++] = pinned;\n\n                int3 regionMin = regionCoord * edge;\n                int3 regionMaxExclusive = regionMin + edge;\n'''
new = '''            int edge = VoxelReadGrid.BlocksPerRegionEdge;\n            int3 cacheMaxExclusive = cacheOrigin + BrickCacheEdge;\n            int3 coreMinWorldBlock = cacheOrigin + BrickCachePadding;\n            int3 minRegion = cacheOrigin >> VoxelReadGrid.BlocksPerRegionEdgeLog2;\n            int3 maxRegion = (cacheMaxExclusive - 1) >> VoxelReadGrid.BlocksPerRegionEdgeLog2;\n\n            for (int rz = minRegion.z; rz <= maxRegion.z; rz++)\n            for (int ry = minRegion.y; ry <= maxRegion.y; ry++)\n            for (int rx = minRegion.x; rx <= maxRegion.x; rx++)\n            {\n                int3 regionCoord = new(rx, ry, rz);\n                bool requiredRegion = ExactSnapshotRegionCoverage.RegionIntersectsCore(\n                    regionCoord, edge, coreMinWorldBlock, BricksPerAxis);\n                bool pinnedRegion = source.TryPinRegionBlockRefs(\n                    regionCoord, out PinnedRegionBlockRefs pinned);\n                _exactMetadataRegionCoverage.RecordRegion(requiredRegion, pinnedRegion);\n                if (!pinnedRegion) continue;\n                if (_pinnedRegionCount >= MaxExactSnapshotRegions)\n                {\n                    source.ReleasePinnedRegion(in pinned.Pin);\n                    ReleasePinnedRegionMetadataImmediate();\n                    throw new InvalidOperationException(\n                        "Exact snapshot exceeded the 3x3x3 pinned-region bound.");\n                }\n                _pinnedRegionBlockRefs[_pinnedRegionCount++] = pinned;\n\n                int3 regionMin = regionCoord * edge;\n                int3 regionMaxExclusive = regionMin + edge;\n'''
count = text.count(old)
if count != 1:
    raise SystemExit(f"expected one exact metadata region loop anchor, found {count}")
text = text.replace(old, new, 1)
path.write_text(text)
print("updated exact snapshot coverage to require only core-owning regions")
