from pathlib import Path

path = Path('.claude/plans/voxel-showcase-rendering-repair-v2.md')
text = path.read_text()
old = '''- [x] Add `ExactSnapshotRegionCoverageTests`: every padded-cache region intersection is required, and a failed exact region metadata pin makes the optimistic snapshot incomplete rather than empty (`cfd54a39`).\n- [x] Repair exact snapshot acquisition so incomplete required-region coverage is rejected after already-scheduled metadata jobs finish and retried through the existing bounded discard/requeue lifecycle; no synchronous completion, LOD distance, frame budget, or geometry threshold changes.\n- [ ] Validate the exact-region coverage regression in EditMode and rerun the step-4 lifecycle/LOD coverage gate; only mark the production false-empty defect resolved if `unowned/readyEmpty` drops for the castle view without introducing blocking completion or coverage regressions.\n'''
new = '''- [x] Add the initial `ExactSnapshotRegionCoverageTests` and reject incomplete required-region metadata instead of treating an unavailable core as authoritative empty (`cfd54a39`, `ad9d7c13`).\n- [x] Identify the over-strict halo flaw before crediting that repair: production chunks are at most one storage region wide, but their one-block extraction halo can cross into intentionally non-resident regions. In the showcase, step-4 ground chunks own blocks `[0,32)` in region `y=0` while their halo reaches region `y=-1`; `ShowcaseWorld.SurfaceLayerSpan` clamps residency to `y>=0`, so requiring every padded halo region would retry those chunks forever.\n- [x] Correct exact snapshot coverage so only regions intersecting the unpadded owned core are required; available halo metadata is still copied, unavailable halo ranges remain cleared for the optimistic build, and unavailable core metadata still rejects/retries through the existing bounded lifecycle. Add regressions proving a missing core pin rejects the snapshot while the step-4 negative-Y halo is optional. No synchronous completion, LOD distance, frame budget, fallback rule, or geometry threshold changes (`7cad2b26`, `d6b38e5f`, `94029f35`).\n- [ ] Validate the corrected core/halo exact-region coverage regression in EditMode and rerun the step-4 lifecycle/LOD coverage gate; only mark the production false-empty defect resolved if `unowned/readyEmpty` drops for the castle view without introducing blocking completion, permanent retry backlog, or coverage regressions.\n'''
count = text.count(old)
if count != 1:
    raise SystemExit(f'expected one exact-region checklist block, found {count}')
path.write_text(text.replace(old, new, 1))
print('updated exact-region coverage checklist for core-versus-halo semantics')
