using System;
using System.IO;
using System.Security.Cryptography;
using NUnit.Framework;
using UnityEngine;

namespace VoxelEngine.Tests.PlayMode
{
    /// <summary>
    /// CI-only bridge for refreshing the checked-in deterministic showcase startup image.
    /// The single-test workflow bakes the world before PlayMode, then this focused test copies
    /// exactly those generated bytes under Artifacts/SingleTest so the agent can commit them.
    /// Remove this bridge after the refreshed binary is committed.
    /// </summary>
    public sealed class ShowcaseBakeArtifactTests
    {
        [Test]
        public void FreshShowcaseBakeIsCapturedForCommit()
        {
            const string source = "Assets/Resources/VoxelShowcase/ShowcaseWorld.bytes";
            const string destination = "Artifacts/SingleTest/ShowcaseWorld.bytes";

            Assert.True(File.Exists(source), "Single-test setup did not produce the showcase bake.");
            byte[] bytes = File.ReadAllBytes(source);
            Assert.Greater(bytes.Length, 1024 * 1024,
                "Showcase bake is unexpectedly tiny and should not replace the production asset.");
            Assert.Less(bytes.Length, 20 * 1024 * 1024,
                "Current showcase bake should remain in the compact production format; a much larger file likely means a stale startup image survived setup.");

            string directory = Path.GetDirectoryName(destination);
            if (string.IsNullOrEmpty(directory))
                throw new InvalidOperationException("Invalid bake artifact destination.");
            Directory.CreateDirectory(directory);
            File.WriteAllBytes(destination, bytes);

            using SHA256 sha = SHA256.Create();
            string digest = BitConverter.ToString(sha.ComputeHash(bytes)).Replace("-", "").ToLowerInvariant();
            Debug.Log($"### SHOWCASE_BAKE_ARTIFACT bytes={bytes.Length} sha256={digest} path={destination}");
        }
    }
}
