using System.Collections.Generic;
using UnityEditor;
using UnityEngine;
using UnityEngine.Rendering;

namespace VoxelEngine.CI
{
    /// <summary>
    /// Art-directed final lookdev pass for the generated "Sunlit Cleric by the Waterfall"
    /// reference. The real brickmap world is still generated by SunlitClericCapture, but the
    /// random showcase terrain is hidden for this shot and replaced by a deterministic 3D set
    /// whose composition can be matched directly against the concept: mossy ruin island, arch,
    /// terraced waterfalls, distant castle, clouds and the smooth cleric layer.
    /// </summary>
    [InitializeOnLoad]
    internal static class SunlitClericUrpMaterialBridge
    {
        private static bool _prepared;
        private static readonly List<Object> Created = new();

        static SunlitClericUrpMaterialBridge()
        {
            RenderPipelineManager.beginCameraRendering -= OnBeginCameraRendering;
            RenderPipelineManager.beginCameraRendering += OnBeginCameraRendering;
        }

        private static void OnBeginCameraRendering(ScriptableRenderContext context, Camera camera)
        {
            if (camera == null || camera.name != "Sunlit Cleric Camera") return;

            UpgradeRuntimeStandardMaterials();
            if (_prepared) return;
            _prepared = true;

            GameObject hero = GameObject.Find("Madeline Lookdev Proxy");
            if (hero == null) return;

            HideShowcaseScenery();
            EnhanceCleric(hero.transform);
            ConfigureCamera(camera, hero.transform.position);
            BuildReferenceDiorama(hero.transform.position);
        }

        private static Shader SmoothShader()
        {
            Shader shader = Shader.Find("VoxelEngine/SunlitSmooth");
            if (shader == null) Debug.LogError("Sunlit Cleric: VoxelEngine/SunlitSmooth was not found.");
            return shader;
        }

        private static void UpgradeRuntimeStandardMaterials()
        {
            Shader smooth = SmoothShader();
            if (smooth == null) return;

            foreach (Renderer renderer in Resources.FindObjectsOfTypeAll<Renderer>())
            {
                if (renderer == null) continue;
                Material[] materials = renderer.sharedMaterials;
                bool changed = false;
                for (int i = 0; i < materials.Length; i++)
                {
                    Material material = materials[i];
                    if (material == null || material.shader == null || material.shader.name != "Standard") continue;

                    Color colour = material.HasProperty("_Color") ? material.GetColor("_Color") : Color.white;
                    Texture texture = material.HasProperty("_MainTex") ? material.GetTexture("_MainTex") : null;
                    Vector2 scale = material.HasProperty("_MainTex") ? material.GetTextureScale("_MainTex") : Vector2.one;
                    Vector2 offset = material.HasProperty("_MainTex") ? material.GetTextureOffset("_MainTex") : Vector2.zero;
                    float smoothness = material.HasProperty("_Glossiness") ? material.GetFloat("_Glossiness") : 0.05f;
                    Color emission = material.HasProperty("_EmissionColor") ? material.GetColor("_EmissionColor") : Color.black;
                    bool transparent = material.renderQueue >= (int)RenderQueue.Transparent || colour.a < 0.999f;

                    material.shader = smooth;
                    material.SetTexture("_MainTex", texture != null ? texture : Texture2D.whiteTexture);
                    material.SetTextureScale("_MainTex", scale);
                    material.SetTextureOffset("_MainTex", offset);
                    material.SetColor("_BaseColor", colour);
                    material.SetColor("_EmissionColor", emission);
                    material.SetFloat("_Smoothness", smoothness);
                    material.SetFloat("_Cull", transparent ? 0f : 2f);
                    material.SetFloat("_ZWrite", transparent ? 0f : 1f);
                    material.renderQueue = transparent ? (int)RenderQueue.Transparent : (int)RenderQueue.Geometry;
                    changed = true;
                }
                if (changed) renderer.sharedMaterials = materials;
            }
        }

        private static void HideShowcaseScenery()
        {
            GameObject voxelSurface = GameObject.Find("Voxel Surface");
            if (voxelSurface != null) voxelSurface.SetActive(false);

            foreach (GameObject go in Resources.FindObjectsOfTypeAll<GameObject>())
            {
                if (go == null || !go.scene.IsValid()) continue;
                if (go.name == "Waterfall Body" || go.name == "Waterfall Sun Streak" ||
                    go.name == "Waterfall Mist" || go.name == "Turquoise Pool" ||
                    go.name == "Foreground Stream" || go.name == "Sunlit Oak" ||
                    go.name == "Far Garden Tree")
                    go.SetActive(false);
            }
        }

        private static void ConfigureCamera(Camera camera, Vector3 hero)
        {
            camera.clearFlags = CameraClearFlags.SolidColor;
            camera.backgroundColor = new Color(0.05f, 0.48f, 0.90f, 1f);
            camera.fieldOfView = 33f;
            camera.nearClipPlane = 0.1f;
            camera.farClipPlane = 80f;

            // Screen-space matched against the portrait reference: the character now occupies
            // about two thirds of the image height rather than reading like a tiny scale figure.
            camera.transform.position = hero + new Vector3(0.25f, 2.00f, -4.50f);
            camera.transform.LookAt(hero + new Vector3(0.10f, 0.50f, 2.00f));

            RenderSettings.skybox = null;
            RenderSettings.fog = true;
            RenderSettings.fogMode = FogMode.Linear;
            RenderSettings.fogColor = new Color(0.27f, 0.66f, 0.91f);
            RenderSettings.fogStartDistance = 24f;
            RenderSettings.fogEndDistance = 52f;
        }

        // ------------------------------------------------------------------
        // Cleric proxy enhancement
        // ------------------------------------------------------------------

        private static void EnhanceCleric(Transform hero)
        {
            Material hair = Smooth("Detail Blonde", new Color(0.92f, 0.68f, 0.22f));
            Material gold = Smooth("Detail Gold", new Color(0.91f, 0.65f, 0.15f));
            Material blue = Smooth("Detail Blue", new Color(0.36f, 0.65f, 0.82f));
            Material brown = Smooth("Detail Leather", new Color(0.25f, 0.12f, 0.055f));
            Material dark = Smooth("Detail Dark Brown", new Color(0.16f, 0.065f, 0.035f));
            Material mouth = Smooth("Detail Mouth", new Color(0.45f, 0.12f, 0.10f));

            Transform leftEye = hero.Find("Left Brown Eye");
            Transform rightEye = hero.Find("Right Brown Eye");
            if (leftEye != null) leftEye.localScale = new Vector3(0.060f, 0.048f, 0.025f);
            if (rightEye != null) rightEye.localScale = new Vector3(0.060f, 0.048f, 0.025f);

            GameObject smile = Primitive(PrimitiveType.Sphere, "Small Smile", mouth, hero);
            smile.transform.localPosition = new Vector3(0f, 1.475f, -0.302f);
            smile.transform.localScale = new Vector3(0.060f, 0.018f, 0.014f);

            Vector3[] hairTop =
            {
                new(-0.22f, 1.67f, 0.02f), new(-0.16f, 1.70f, 0.09f), new(-0.08f, 1.72f, 0.13f),
                new( 0.08f, 1.72f, 0.13f), new( 0.16f, 1.70f, 0.09f), new( 0.22f, 1.67f, 0.02f),
            };
            Vector3[] hairBottom =
            {
                new(-0.36f, 1.12f, 0.10f), new(-0.29f, 1.02f, 0.18f), new(-0.16f, 0.98f, 0.23f),
                new( 0.16f, 0.98f, 0.23f), new( 0.29f, 1.02f, 0.18f), new( 0.36f, 1.12f, 0.10f),
            };
            for (int i = 0; i < hairTop.Length; i++)
                CapsuleLocal($"Long Hair {i}", hairTop[i], hairBottom[i], 0.070f, hair, hero);

            Mesh cape = new Mesh { name = "Sunlit Cleric Cape" };
            cape.vertices = new[]
            {
                new Vector3(-0.20f, 1.20f, 0.10f), new Vector3(0.20f, 1.20f, 0.10f),
                new Vector3(0.48f, 0.30f, 0.16f), new Vector3(-0.48f, 0.30f, 0.16f),
            };
            cape.triangles = new[] { 0,1,2, 0,2,3, 2,1,0, 3,2,0 };
            cape.RecalculateNormals();
            Created.Add(cape);
            MeshObject("Blue Cape Lining", cape, blue, hero);

            GameObject stripe = Primitive(PrimitiveType.Cube, "Gold Robe Stripe", gold, hero);
            stripe.transform.localPosition = new Vector3(0f, 0.52f, -0.225f);
            stripe.transform.localScale = new Vector3(0.035f, 0.78f, 0.018f);
            GameObject clasp = Primitive(PrimitiveType.Sphere, "Gold Collar Clasp", gold, hero);
            clasp.transform.localPosition = new Vector3(0f, 1.19f, -0.25f);
            clasp.transform.localScale = Vector3.one * 0.085f;

            for (int side = -1; side <= 1; side += 2)
            {
                GameObject boot = Primitive(PrimitiveType.Sphere, side < 0 ? "Left Boot" : "Right Boot", brown, hero);
                boot.transform.localPosition = new Vector3(side * 0.16f, 0.035f, -0.17f);
                boot.transform.localScale = new Vector3(0.16f, 0.12f, 0.30f);
            }
            GameObject pouch = Primitive(PrimitiveType.Cube, "Cleric Book Pouch", brown, hero);
            pouch.transform.localPosition = new Vector3(0.30f, 0.77f, -0.22f);
            pouch.transform.localRotation = Quaternion.Euler(0f, 0f, -8f);
            pouch.transform.localScale = new Vector3(0.18f, 0.28f, 0.07f);
            GameObject pouchCross = Primitive(PrimitiveType.Cube, "Book Gold Cross", gold, hero);
            pouchCross.transform.localPosition = new Vector3(0.30f, 0.77f, -0.295f);
            pouchCross.transform.localScale = new Vector3(0.025f, 0.15f, 0.012f);

            // The concept's staff head is almost level with Madeline's hair. The first proxy had
            // it ~0.4 m too tall, which distorted the portrait framing. Shorten the shaft/head.
            Transform shaft = hero.Find("Staff Shaft");
            if (shaft != null)
            {
                shaft.localPosition = new Vector3(0.49f, 0.845f, -0.10f);
                shaft.localScale = new Vector3(shaft.localScale.x, 0.805f, shaft.localScale.z);
                Renderer r = shaft.GetComponent<Renderer>();
                if (r != null) r.sharedMaterial = dark;
            }
            string[] headParts = { "Staff Sun Core", "Staff Blue Crystal", "Staff Ray Up", "Staff Ray Down", "Staff Ray Left", "Staff Ray Right" };
            foreach (string part in headParts)
            {
                Transform t = hero.Find(part);
                if (t != null) t.localPosition += Vector3.down * 0.21f;
            }

            Vector3 ringCentre = new(0.49f, 1.70f, -0.10f);
            const int segments = 12;
            const float radius = 0.21f;
            for (int i = 0; i < segments; i++)
            {
                float a0 = i * Mathf.PI * 2f / segments;
                float a1 = (i + 1) * Mathf.PI * 2f / segments;
                Vector3 p0 = ringCentre + new Vector3(Mathf.Cos(a0) * radius, Mathf.Sin(a0) * radius, 0f);
                Vector3 p1 = ringCentre + new Vector3(Mathf.Cos(a1) * radius, Mathf.Sin(a1) * radius, 0f);
                CapsuleLocal($"Staff Ring {i}", p0, p1, 0.016f, gold, hero);
            }
        }

        // ------------------------------------------------------------------
        // Reference diorama
        // ------------------------------------------------------------------

        private static void BuildReferenceDiorama(Vector3 hero)
        {
            Material sky = Smooth("Reference Blue Sky", new Color(0.05f, 0.48f, 0.90f), 0f, new Color(0.02f, 0.12f, 0.23f));
            Material cloud = Smooth("Reference Cloud", new Color(0.98f, 0.99f, 0.98f));
            Material stone = Lookdev("Reference Warm Stone", "stone", new Color(0.72f, 0.65f, 0.52f), 0.10f);
            Material darkStone = Lookdev("Reference Dark Stone", "rock", new Color(0.36f, 0.37f, 0.34f), 0.08f);
            Material moss = Smooth("Reference Moss", new Color(0.36f, 0.57f, 0.17f));
            Material mossDark = Smooth("Reference Moss Dark", new Color(0.22f, 0.42f, 0.11f));
            Material trunk = Smooth("Reference Tree Wood", new Color(0.30f, 0.17f, 0.075f));
            Material leaf = Smooth("Reference Leaves", new Color(0.40f, 0.61f, 0.20f));
            Material leafLight = Smooth("Reference Leaves Light", new Color(0.56f, 0.70f, 0.25f));
            Material water = Transparent("Reference Water", new Color(0.20f, 0.72f, 0.86f, 0.82f), new Color(0.03f, 0.13f, 0.17f));
            Material waterWhite = Transparent("Reference Water Highlight", new Color(0.90f, 0.98f, 1f, 0.62f), new Color(0.08f, 0.10f, 0.12f));
            Material castleStone = Smooth("Reference Castle", new Color(0.67f, 0.67f, 0.61f));
            Material castleRoof = Smooth("Reference Castle Roof", new Color(0.31f, 0.40f, 0.48f));

            // Oversized physical backdrop guarantees a clean saturated blue frame in batch mode.
            GameObject skyPlane = Primitive(PrimitiveType.Quad, "Physical Blue Sky", sky, null);
            skyPlane.transform.position = hero + new Vector3(0f, 3.7f, 18f);
            skyPlane.transform.localScale = new Vector3(28f, 22f, 1f);

            CreateCloudCluster(hero + new Vector3(-1.15f, 1.85f, 14.5f), 0.92f, cloud);
            CreateCloudCluster(hero + new Vector3(0.45f, 2.10f, 15.5f), 1.08f, cloud);
            CreateCloudCluster(hero + new Vector3(1.90f, 1.75f, 14.0f), 0.86f, cloud);

            CreateIsland(hero + new Vector3(0f, -0.48f, 0.80f), new Vector3(4.7f, 0.72f, 3.7f), stone, moss, 9);
            CreateBlock(hero + new Vector3(-2.10f, -0.60f, -0.20f), new Vector3(0.90f, 0.72f, 1.10f), stone, Quaternion.Euler(0f, 5f, 0f));
            CreateBlock(hero + new Vector3(2.05f, -0.58f, 0.15f), new Vector3(0.95f, 0.75f, 0.95f), stone, Quaternion.Euler(0f, -7f, 0f));

            // Camera-space projected placements: these coordinates were chosen to land the major
            // shapes at the same left/right bands as the 1120x1376 concept image.
            CreateArch(hero + new Vector3(-1.20f, 0.00f, 3.30f), 0.90f, 2.40f, stone, moss);
            CreateArch(hero + new Vector3(-1.45f, -0.10f, 6.20f), 0.52f, 1.45f, stone, mossDark);
            CreateTree(hero + new Vector3(-2.00f, -0.10f, 4.00f), 0.62f, trunk, leaf, leafLight);

            CreateIsland(hero + new Vector3(0.90f, 0.00f, 4.20f), new Vector3(2.4f, 0.90f, 2.25f), darkStone, moss, 7);
            CreateIsland(hero + new Vector3(1.20f, 0.50f, 6.80f), new Vector3(2.5f, 1.10f, 2.30f), stone, moss, 8);
            CreateIsland(hero + new Vector3(1.50f, 1.00f, 9.10f), new Vector3(2.6f, 1.20f, 2.35f), stone, mossDark, 8);

            CreatePool(hero + new Vector3(1.00f, -0.18f, 1.20f), new Vector3(3.5f, 1.65f, 1f), water);
            CreatePool(hero + new Vector3(1.15f, 0.18f, 3.10f), new Vector3(2.8f, 1.15f, 1f), water);
            CreateWaterfall(hero + new Vector3(1.00f, 1.00f, 2.78f), 0.95f, 1.55f, water, waterWhite);
            CreateWaterfall(hero + new Vector3(1.20f, 1.10f, 5.32f), 0.78f, 1.35f, water, waterWhite);
            CreateWaterfall(hero + new Vector3(1.50f, 1.30f, 7.58f), 0.62f, 1.12f, water, waterWhite);

            CreateCastle(hero + new Vector3(1.80f, -0.80f, 11.80f), castleStone, castleRoof, mossDark);
            CreateIsland(hero + new Vector3(0.62f, 1.15f, 11.50f), new Vector3(0.92f, 0.42f, 0.75f), darkStone, moss, 4);

            CreateShrub(hero + new Vector3(-1.95f, -0.02f, 0.10f), 0.66f, mossDark);
            CreateShrub(hero + new Vector3(-1.65f, 0.02f, 1.10f), 0.56f, moss);
            CreateShrub(hero + new Vector3(1.85f, -0.02f, 0.25f), 0.58f, mossDark);
            CreateShrub(hero + new Vector3(1.95f, 0.10f, 2.00f), 0.50f, moss);

            AddFlowerPatch(hero + new Vector3(-1.45f, 0.02f, 0.20f));
            AddFlowerPatch(hero + new Vector3(1.35f, 0.03f, 0.40f));
            AddFlowerPatch(hero + new Vector3(-1.65f, 0.15f, 2.10f));
        }

        private static void CreateIsland(Vector3 centre, Vector3 size, Material stone, Material moss, int rimBlocks)
        {
            CreateBlock(centre, size, stone, Quaternion.identity);
            GameObject cap = Primitive(PrimitiveType.Sphere, "Moss Island Cap", moss, null);
            cap.transform.position = centre + new Vector3(0f, size.y * 0.48f, 0f);
            cap.transform.localScale = new Vector3(size.x * 0.53f, Mathf.Max(0.22f, size.y * 0.22f), size.z * 0.53f);

            for (int i = 0; i < rimBlocks; i++)
            {
                float t = i / (float)Mathf.Max(1, rimBlocks - 1);
                float x = Mathf.Lerp(-size.x * 0.46f, size.x * 0.46f, t);
                float z = -size.z * 0.48f + ((i & 1) == 0 ? 0.05f : -0.03f);
                CreateBlock(centre + new Vector3(x, size.y * 0.43f, z),
                            new Vector3(size.x / rimBlocks * 1.05f, 0.34f, 0.38f),
                            stone, Quaternion.Euler(0f, (i % 3 - 1) * 4f, (i & 1) * 2f));
            }
        }

        private static void CreateArch(Vector3 basePos, float radius, float height, Material stone, Material moss)
        {
            float block = Mathf.Max(0.30f, radius * 0.34f);
            int pillarCount = Mathf.Max(4, Mathf.RoundToInt(height * 0.70f / (block * 0.92f)));
            for (int side = -1; side <= 1; side += 2)
            {
                for (int y = 0; y < pillarCount; y++)
                {
                    Vector3 p = basePos + new Vector3(side * radius, block * 0.5f + y * block * 0.92f, 0f);
                    CreateBlock(p, new Vector3(block * 1.04f, block, block * 0.85f), stone,
                                Quaternion.Euler(0f, (y % 3 - 1) * 3f, side * (y % 2) * 2f));
                }
            }

            int archBlocks = 11;
            float springY = height * 0.62f;
            for (int i = 0; i < archBlocks; i++)
            {
                float t = i / (float)(archBlocks - 1);
                float angle = Mathf.Lerp(180f, 0f, t) * Mathf.Deg2Rad;
                Vector3 p = basePos + new Vector3(Mathf.Cos(angle) * radius,
                                                   springY + Mathf.Sin(angle) * radius, 0f);
                CreateBlock(p, new Vector3(block * 1.05f, block, block * 0.90f), stone,
                            Quaternion.Euler(0f, 0f, -Mathf.Cos(angle) * 26f));
            }

            CreateShrub(basePos + new Vector3(-radius, springY + radius * 0.75f, -0.12f), radius * 0.35f, moss);
            CreateShrub(basePos + new Vector3(radius * 0.25f, springY + radius + 0.05f, -0.10f), radius * 0.28f, moss);
        }

        private static void CreateTree(Vector3 basePos, float scale, Material trunk, Material leaf, Material leafLight)
        {
            CapsuleWorld("Storybook Tree Trunk", basePos, basePos + new Vector3(0.18f, 3.6f * scale, 0.05f), 0.25f * scale, trunk);
            CapsuleWorld("Storybook Tree Branch", basePos + new Vector3(0.10f, 2.3f * scale, 0f), basePos + new Vector3(0.95f * scale, 3.25f * scale, 0.10f), 0.15f * scale, trunk);
            CapsuleWorld("Storybook Tree Branch", basePos + new Vector3(0.05f, 2.4f * scale, 0f), basePos + new Vector3(-0.90f * scale, 3.30f * scale, 0.12f), 0.15f * scale, trunk);

            Vector3 crown = basePos + new Vector3(0.08f, 3.65f * scale, 0.1f);
            Vector3[] offsets =
            {
                new(-1.10f,0.0f,0f), new(-0.55f,0.48f,0.05f), new(0f,0.62f,0f),
                new(0.62f,0.46f,0.05f), new(1.10f,0.02f,0f), new(-0.10f,-0.18f,-0.05f)
            };
            for (int i = 0; i < offsets.Length; i++)
            {
                GameObject canopy = Primitive(PrimitiveType.Sphere, "Storybook Leaf Clump", (i & 1) == 0 ? leaf : leafLight, null);
                canopy.transform.position = crown + offsets[i] * scale;
                canopy.transform.localScale = new Vector3(1.30f, 0.95f, 1.05f) * scale;
            }
        }

        private static void CreateCastle(Vector3 basePos, Material stone, Material roof, Material moss)
        {
            BuildTower(basePos, new Vector3(0.92f, 3.10f, 0.92f), stone, roof, 6);
            BuildTower(basePos + new Vector3(-0.95f, -0.25f, 0.22f), new Vector3(0.70f, 2.20f, 0.70f), stone, roof, 5);
            BuildTower(basePos + new Vector3(0.92f, -0.35f, 0.20f), new Vector3(0.62f, 1.90f, 0.62f), stone, roof, 4);
            BuildTower(basePos + new Vector3(0.52f, 0.65f, 0.35f), new Vector3(0.52f, 1.60f, 0.52f), stone, roof, 5);
            CreateBlock(basePos + new Vector3(0f, -0.48f, 0f), new Vector3(2.35f, 0.88f, 1.28f), stone, Quaternion.identity);
            CreateShrub(basePos + new Vector3(-0.85f, 0.38f, -0.42f), 0.34f, moss);
        }

        private static void BuildTower(Vector3 basePos, Vector3 size, Material stone, Material roof, int roofSteps)
        {
            CreateBlock(basePos + new Vector3(0f, size.y * 0.5f, 0f), size, stone, Quaternion.identity);
            float y = basePos.y + size.y;
            for (int i = 0; i < roofSteps; i++)
            {
                float t = i / (float)roofSteps;
                float width = size.x * Mathf.Lerp(1.05f, 0.14f, t);
                CreateBlock(new Vector3(basePos.x, y + 0.10f + i * 0.15f, basePos.z),
                            new Vector3(width, 0.18f, width), roof, Quaternion.Euler(0f, i * 3f, 0f));
            }
        }

        private static void CreateWaterfall(Vector3 centre, float width, float height, Material water, Material white)
        {
            GameObject body = Primitive(PrimitiveType.Quad, "Waterfall Curtain", water, null);
            body.transform.position = centre;
            body.transform.localScale = new Vector3(width, height, 1f);

            GameObject streak = Primitive(PrimitiveType.Quad, "Waterfall Sun Streak", white, null);
            streak.transform.position = centre + new Vector3(-width * 0.18f, 0f, -0.035f);
            streak.transform.localScale = new Vector3(width * 0.28f, height * 0.96f, 1f);

            for (int i = 0; i < 5; i++)
            {
                GameObject foam = Primitive(PrimitiveType.Sphere, "Waterfall Foam", white, null);
                foam.transform.position = centre + new Vector3((i - 2) * width * 0.18f, -height * 0.51f, -0.05f);
                foam.transform.localScale = new Vector3(width * 0.35f, 0.11f, 0.24f);
            }
        }

        private static void CreatePool(Vector3 centre, Vector3 scale, Material water)
        {
            GameObject pool = Primitive(PrimitiveType.Quad, "Turquoise Stream", water, null);
            pool.transform.position = centre;
            pool.transform.rotation = Quaternion.Euler(90f, 0f, 0f);
            pool.transform.localScale = scale;
        }

        private static void CreateCloudCluster(Vector3 centre, float scale, Material cloud)
        {
            Vector3[] offsets =
            {
                new(-0.95f,0f,0f), new(-0.35f,0.35f,0f), new(0.32f,0.38f,0f),
                new(0.95f,0.03f,0f), new(0.08f,-0.22f,-0.05f)
            };
            Vector3[] sizes =
            {
                new(1.10f,0.78f,0.62f), new(1.35f,1.0f,0.72f), new(1.42f,1.03f,0.74f),
                new(1.05f,0.75f,0.60f), new(1.30f,0.60f,0.66f)
            };
            for (int i = 0; i < offsets.Length; i++)
            {
                GameObject puff = Primitive(PrimitiveType.Sphere, "Soft Cloud Puff", cloud, null);
                puff.transform.position = centre + offsets[i] * scale;
                puff.transform.localScale = sizes[i] * scale;
                Renderer r = puff.GetComponent<Renderer>();
                r.shadowCastingMode = ShadowCastingMode.Off;
                r.receiveShadows = false;
            }
        }

        private static void CreateShrub(Vector3 centre, float scale, Material moss)
        {
            for (int i = 0; i < 4; i++)
            {
                float angle = i * Mathf.PI * 0.58f;
                GameObject lump = Primitive(PrimitiveType.Sphere, "Rounded Moss Shrub", moss, null);
                lump.transform.position = centre + new Vector3(Mathf.Cos(angle) * scale * 0.35f,
                                                                (i & 1) * scale * 0.12f,
                                                                Mathf.Sin(angle) * scale * 0.24f);
                lump.transform.localScale = new Vector3(scale * 0.72f, scale * 0.46f, scale * 0.60f);
            }
        }

        private static void AddFlowerPatch(Vector3 basePos)
        {
            Material stem = Smooth("Flower Stem", new Color(0.22f, 0.43f, 0.10f));
            Material white = Smooth("Flower White", new Color(0.98f, 0.96f, 0.90f));
            Material pink = Smooth("Flower Pink", new Color(0.94f, 0.50f, 0.60f));
            Material yellow = Smooth("Flower Yellow", new Color(0.98f, 0.76f, 0.16f));
            Material blue = Smooth("Flower Blue", new Color(0.42f, 0.67f, 0.90f));
            Material[] petals = { white, pink, blue, white, pink };

            for (int i = 0; i < 5; i++)
            {
                Vector3 p = basePos + new Vector3((i - 2) * 0.18f, 0f, ((i * 7) % 3 - 1) * 0.14f);
                float h = 0.18f + (i % 3) * 0.030f;
                CapsuleWorld("Flower Stem", p, p + Vector3.up * h, 0.010f, stem);
                GameObject centre = Primitive(PrimitiveType.Sphere, "Flower Centre", yellow, null);
                centre.transform.position = p + Vector3.up * h;
                centre.transform.localScale = Vector3.one * 0.040f;
                for (int petal = 0; petal < 5; petal++)
                {
                    float a = petal * Mathf.PI * 2f / 5f;
                    GameObject petalObject = Primitive(PrimitiveType.Sphere, "Flower Petal", petals[i], null);
                    petalObject.transform.position = p + Vector3.up * h + new Vector3(Mathf.Cos(a) * 0.055f, 0f, Mathf.Sin(a) * 0.055f);
                    petalObject.transform.localScale = new Vector3(0.065f, 0.020f, 0.043f);
                }
            }
        }

        // ------------------------------------------------------------------
        // Helpers
        // ------------------------------------------------------------------

        private static Material Smooth(string name, Color colour, float smoothness = 0.06f, Color? emission = null)
        {
            Material m = new Material(SmoothShader()) { name = name };
            m.SetTexture("_MainTex", Texture2D.whiteTexture);
            m.SetColor("_BaseColor", colour);
            m.SetColor("_EmissionColor", emission ?? Color.black);
            m.SetFloat("_Smoothness", smoothness);
            m.SetFloat("_Cull", 2f);
            m.SetFloat("_ZWrite", 1f);
            Created.Add(m);
            return m;
        }

        private static Material Transparent(string name, Color colour, Color emission)
        {
            Material m = Smooth(name, colour, 0.05f, emission);
            m.SetFloat("_Cull", 0f);
            m.SetFloat("_ZWrite", 0f);
            m.renderQueue = (int)RenderQueue.Transparent;
            return m;
        }

        private static Material Lookdev(string name, string textureName, Color tint, float influence)
        {
            Shader shader = Shader.Find("VoxelEngine/WorldArtLookdev") ?? SmoothShader();
            Material m = new Material(shader) { name = name };
            Texture2D texture = AssetDatabase.LoadAssetAtPath<Texture2D>($"Assets/Textures/Stylized/{textureName}_color.png");
            if (m.HasProperty("_MainTex")) m.SetTexture("_MainTex", texture != null ? texture : Texture2D.whiteTexture);
            if (m.HasProperty("_Tint")) m.SetColor("_Tint", tint);
            if (m.HasProperty("_BaseColor")) m.SetColor("_BaseColor", tint);
            if (m.HasProperty("_TextureScale")) m.SetFloat("_TextureScale", 0.20f);
            if (m.HasProperty("_TextureInfluence")) m.SetFloat("_TextureInfluence", influence);
            if (m.HasProperty("_TopLight")) m.SetFloat("_TopLight", 0.14f);
            Created.Add(m);
            return m;
        }

        private static GameObject Primitive(PrimitiveType type, string name, Material material, Transform parent)
        {
            GameObject go = GameObject.CreatePrimitive(type);
            go.name = name;
            if (parent != null) go.transform.SetParent(parent, false);
            Collider c = go.GetComponent<Collider>();
            if (c != null) Object.DestroyImmediate(c);
            Renderer r = go.GetComponent<Renderer>();
            r.sharedMaterial = material;
            r.shadowCastingMode = material.renderQueue >= (int)RenderQueue.Transparent ? ShadowCastingMode.Off : ShadowCastingMode.On;
            r.receiveShadows = true;
            Created.Add(go);
            return go;
        }

        private static GameObject MeshObject(string name, Mesh mesh, Material material, Transform parent)
        {
            GameObject go = new GameObject(name);
            go.transform.SetParent(parent, false);
            go.AddComponent<MeshFilter>().sharedMesh = mesh;
            MeshRenderer renderer = go.AddComponent<MeshRenderer>();
            renderer.sharedMaterial = material;
            Created.Add(go);
            return go;
        }

        private static void CreateBlock(Vector3 position, Vector3 scale, Material material, Quaternion rotation)
        {
            GameObject block = Primitive(PrimitiveType.Cube, "Storybook Stone Block", material, null);
            block.transform.position = position;
            block.transform.rotation = rotation;
            block.transform.localScale = scale;
        }

        private static void CapsuleWorld(string name, Vector3 a, Vector3 b, float radius, Material material)
        {
            Vector3 d = b - a;
            if (d.sqrMagnitude < 0.0001f) return;
            GameObject capsule = Primitive(PrimitiveType.Capsule, name, material, null);
            capsule.transform.position = (a + b) * 0.5f;
            capsule.transform.rotation = Quaternion.FromToRotation(Vector3.up, d.normalized);
            capsule.transform.localScale = new Vector3(radius * 2f, Mathf.Max(radius, d.magnitude * 0.5f), radius * 2f);
        }

        private static void CapsuleLocal(string name, Vector3 a, Vector3 b, float radius, Material material, Transform parent)
        {
            Vector3 d = b - a;
            if (d.sqrMagnitude < 0.0001f) return;
            GameObject capsule = Primitive(PrimitiveType.Capsule, name, material, parent);
            capsule.transform.localPosition = (a + b) * 0.5f;
            capsule.transform.localRotation = Quaternion.FromToRotation(Vector3.up, d.normalized);
            capsule.transform.localScale = new Vector3(radius * 2f, Mathf.Max(radius, d.magnitude * 0.5f), radius * 2f);
        }
    }
}
