using System.IO;
using UnityEditor;
using UnityEngine;

namespace VoxelEngine.CI
{
    [InitializeOnLoad]
    internal static class WaterStudyAlphaPostprocess
    {
        static WaterStudyAlphaPostprocess()
        {
            EditorApplication.quitting += FixWaterStudyAlpha;
        }

        private static void FixWaterStudyAlpha()
        {
            string root = Directory.GetParent(Application.dataPath).FullName;
            string path = Path.Combine(root, "Artifacts", "Water", "water-study.png");
            if (!File.Exists(path))
                return;

            var texture = new Texture2D(2, 2, TextureFormat.RGBA32, false, false);
            try
            {
                if (!texture.LoadImage(File.ReadAllBytes(path), false))
                    return;

                Color32[] pixels = texture.GetPixels32();
                for (int i = 0; i < pixels.Length; i++)
                {
                    // URP/Metal capture on this runner leaves the transparent camera clear
                    // at alpha ~= 195. Remap that clear value to true transparency while
                    // preserving the MSAA edge coverage generated by the water geometry.
                    float t = Mathf.Clamp01((pixels[i].a - 200f) / 55f);
                    t = t * t * (3f - 2f * t);
                    pixels[i].a = (byte)Mathf.RoundToInt(t * 255f);
                }

                texture.SetPixels32(pixels);
                texture.Apply(false, false);
                File.WriteAllBytes(path, texture.EncodeToPNG());
                Debug.Log("Postprocessed water-study alpha to true transparency.");
            }
            finally
            {
                Object.DestroyImmediate(texture);
            }
        }
    }
}
