namespace VoxelEngine.Characters.Api
{
    /// <summary>
    /// Stable category emitted by the offline character factory for equippable parts.
    /// Character bodies are generated by their own pipeline and are not equipment.
    /// </summary>
    public enum CharacterPartKind : byte
    {
        Clothing = 0,
        Weapon = 1,
        Accessory = 2
    }
}
