using System;
using System.Diagnostics;
using System.IO;
using System.Security.Cryptography;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;
using VoxelEngine.Showcase;
using VoxelEngine.Showcase.Editor;

namespace VoxelEngine.Tests.EditMode
{
    /// <summary>
    /// Generates the Mountain Dragon startup image through the production baker and preserves the
    /// exact generated pair in the targeted-test artifact tree so it can be promoted without
    /// reconstructing or weakening provenance.
    /// </summary>
    public sealed class MountainDragonStartupBakeGenerationTests
    {
        private const string BakeAssetPath =
            "Assets/Resources/VoxelShowcase/ShowcaseWorld.bytes";

        [Test]
        public void ProductionBakerGeneratesValidatedStartupPairAndExportsExactEvidence()
        {
            string projectRoot = Path.GetFullPath(Path.Combine(Application.dataPath, ".."));
            string bakePath = Path.Combine(projectRoot, BakeAssetPath);
            string manifestPath = Path.Combine(
                projectRoot,
                ShowcaseStartupBakeContract.ManifestAssetPath);

            // Runner workspaces may contain the stale checked-in payload. Remove only generated
            // data, never their .meta files, so a passing test proves this invocation authored both
            // members of the provenance pair.
            DeleteGeneratedData(bakePath);
            DeleteGeneratedData(manifestPath);
            AssetDatabase.Refresh(ImportAssetOptions.ForceUpdate);

            var stopwatch = Stopwatch.StartNew();
            ShowcaseWorldBaker.BakeShowcaseWorld();
            stopwatch.Stop();

            Assert.That(File.Exists(bakePath), Is.True,
                "The production baker must write the Voxel Showcase startup payload.");
            Assert.That(File.Exists(manifestPath), Is.True,
                "The production baker must write the provenance manifest with the payload.");

            byte[] bytes = File.ReadAllBytes(bakePath);
            string manifest = File.ReadAllText(manifestPath);
            Assert.That(bytes.Length, Is.GreaterThan(0),
                "The generated startup payload must not be empty.");
            Assert.DoesNotThrow(
                () => ShowcaseStartupBakeContract.Validate(bytes, manifest),
                "The production-generated manifest must validate the exact generated bytes.");

            string evidenceDirectory = Path.Combine(
                projectRoot,
                "Artifacts",
                "SingleTest",
                "MountainDragonStartupBake");
            Directory.CreateDirectory(evidenceDirectory);
            File.Copy(
                bakePath,
                Path.Combine(evidenceDirectory, "ShowcaseWorld.bytes"),
                true);
            File.Copy(
                manifestPath,
                Path.Combine(evidenceDirectory, "ShowcaseWorld.manifest.txt"),
                true);

            string sha256;
            using (SHA256 hash = SHA256.Create())
                sha256 = ToLowerHex(hash.ComputeHash(bytes));

            string evidence =
                $"sourceSha={Environment.GetEnvironmentVariable("GITHUB_SHA") ?? string.Empty}\n" +
                $"sizeBytes={bytes.LongLength}\n" +
                $"sha256={sha256}\n" +
                $"contentSignature=0x{ShowcaseStartupBakeContract.RequiredContentSignature:X8}\n" +
                $"elapsedSeconds={stopwatch.Elapsed.TotalSeconds:F3}\n";
            File.WriteAllText(
                Path.Combine(evidenceDirectory, "ShowcaseWorld.evidence.txt"),
                evidence);

            UnityEngine.Debug.Log(
                $"MOUNTAIN_DRAGON_BAKE_GENERATED size={bytes.LongLength} " +
                $"sha256={sha256} elapsed={stopwatch.Elapsed.TotalSeconds:F3}s");
        }

        private static void DeleteGeneratedData(string path)
        {
            if (File.Exists(path))
                File.Delete(path);
        }

        private static string ToLowerHex(byte[] bytes)
        {
            char[] chars = new char[bytes.Length * 2];
            const string hex = "0123456789abcdef";
            for (int i = 0; i < bytes.Length; i++)
            {
                chars[i * 2] = hex[bytes[i] >> 4];
                chars[i * 2 + 1] = hex[bytes[i] & 0x0f];
            }

            return new string(chars);
        }
    }
}
