using System;

namespace MountingForce.WorldGen.Architecture
{
    /// <summary>
    /// Optional low-level geometry policy for anonymous frontage generated by an architecture style.
    /// Keeping this separate from IArchitectureStyleCompiler preserves source compatibility for style
    /// compilers that only resolve massing, while allowing richer city styles to control voxel/mesh
    /// reconstruction without leaking backend surface ids into architecture.
    /// </summary>
    public interface IUrbanFabricGeometryProfileResolver
    {
        StructureGeometryProfile ResolveUrbanFabricGeometry(
            UrbanFabricIntent intent,
            UrbanFabricForm form);
    }

    /// <summary>
    /// Shared resolution helpers for anonymous city fabric. A registered style can opt into
    /// IUrbanFabricGeometryProfileResolver; otherwise conventional human-settlement geometry is used
    /// as the renderer-neutral fallback so new city grammars do not silently regress to block boxes.
    /// </summary>
    public static class UrbanFabricGeometryProfiles
    {
        public static StructureGeometryProfile Resolve(
            UrbanFabricIntent intent,
            UrbanFabricForm form,
            ArchitectureStyleRegistry styles)
        {
            if (styles == null) throw new ArgumentNullException(nameof(styles));
            IArchitectureStyleCompiler compiler = styles.Require(intent.StyleId);
            if (compiler is IUrbanFabricGeometryProfileResolver geometry)
                return geometry.ResolveUrbanFabricGeometry(intent, form);
            return HumanSettlement(intent, form);
        }

        public static StructureGeometryProfile HumanSettlement(
            UrbanFabricIntent intent,
            UrbanFabricForm form)
        {
            int shellRadius;
            switch (intent.District)
            {
                case DistrictKind.Civic:
                case DistrictKind.Noble:
                    shellRadius = 4;
                    break;
                case DistrictKind.Market:
                    shellRadius = 3;
                    break;
                case DistrictKind.Working:
                    shellRadius = 2;
                    break;
                default:
                    shellRadius = 2;
                    break;
            }

            // Very small anonymous modules should not spend most of their silhouette on a corner
            // fillet. Clamp from the resolved local form instead of the settlement envelope.
            int localHalfExtent = Math.Max(1, Math.Min(form.WidthDm, form.DepthDm) / 2);
            shellRadius = Math.Min(shellRadius, Math.Max(1, localHalfExtent / 8));

            int foundationRadius = Math.Max(1, shellRadius - 1);
            int openingRadius = shellRadius >= 3 ? 2 : 1;
            int detailRadius = shellRadius >= 3 ? 2 : 1;
            return new StructureGeometryProfile(
                foundationRadius,
                shellRadius,
                openingRadius,
                detailRadius,
                foundationSurface: StructureSurfaceTreatment.Beveled,
                shellSurface: StructureSurfaceTreatment.ArchitecturalRounded,
                openingSurface: StructureSurfaceTreatment.ArchitecturalRounded,
                detailSurface: StructureSurfaceTreatment.Beveled,
                roofSurface: StructureSurfaceTreatment.Smooth);
        }
    }
}
