#pragma kernel CSProbe

#include "../../Resources/VoxelBrickDensity.hlsl"

int3 _ProbeVoxel;
RWStructuredBuffer<uint> _ProbeOutput;

[numthreads(1, 1, 1)]
void CSProbe(uint3 id : SV_DispatchThreadID)
{
    uint surface;
    uint boundary;
    uint material = ReadMaterial(_ProbeVoxel, surface, boundary);
    _ProbeOutput[0] = material;
    _ProbeOutput[1] = surface;
    _ProbeOutput[2] = boundary;
}
